- name: vaultwarden
  repository: badhouseplants
  version: latest
  extensions:
    - name: Add virtual service to the chartc
      target_dir: templates/extensions
      source_dir: ./examples/extensions/vaultwarden
  patches:
    - name: Git patch 1
      git:
        path: ./examples/patches/git/patch.diff
    - name: Git patch 2
      git:
        path: ./examples/patches/git/patch-2.diff
    - name: yaml-fmt
      custom_command:
        commands:
          - |-
            cat <<EOT >> .yamlfmt
              formatter:
                pad_line_comments: 2
            EOT
          - yamlfmt values.yaml --conf ./yamlfmt.yaml
          - rm -f yamlfmt.yaml
  mirrors:
    - badhouseplants-git
    - custom-command
- name: vaultwarden
  repository: badhouseplants
  version: latest
  extensions:
    - name: Add virtual service to the chartc
      target_dir: templates/extensions
      source_dir: ./examples/extensions/vaultwarden
  patches:
    - name: Git patch 1
      git:
        path: ./examples/patches/git/patch.diff
    - name: Git patch 2
      git:
        path: ./examples/patches/git/patch-2.diff
    - name: yaml-fmt
      custom_command:
        commands:
          - |-
            cat <<EOT >> .yamlfmt
              formatter:
                pad_line_comments: 2
            EOT
          - yamlfmt values.yaml --conf ./yamlfmt.yaml
          - rm -f yamlfmt.yaml
  mirrors:
    - badhouseplants-git
    - custom-command
