# Build a container image
when:
  event:
    - push
steps:
  build:
    image: git.badhouseplants.net/badhouseplants/badhouseplants-builder:555262114ea81f6f286010474527f419b56d33a3
    name: Build helmule operator image
    privileged: true
    environment:
      - PACKAGE_NAME=allanger/helmule
    commands:
      - |
        if [[ "${CI_COMMIT_TAG}" ]]; then
          export CUSTOM_TAG="${CI_COMMIT_TAG}";
        fi
      - build-container
    secrets:
      - gitea_token
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 800Mi
            cpu: 500m
          limits:
            memory: 1000Mi
            cpu: 1000m
